on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Build Image
    steps:
      - name: Build Step
        id: build
        uses: mmullin128/server-config@v1
        with:
          docker-repository: 'docker-repo'
          username: 'username'
          password: 'password'
          gh-owner: 'gh-owner'
          gh-repository: 'gh-repository'
          gh-access-token: 'gh-access-token'
          runner-tag: 'runner-tag'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.vars }}"
