on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Build Image
    steps:
      - name: Build Step
        id: build
        uses: mmullin128/server-config@v1
        with:
          docker-repository: 'mmullin12/pong:latest'
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          gh-repository: $GITHUB_REPOSITORY
          gh-access-token: ${{ secrets.ACCESS_TOKEN }}
          runner-tag: 'dev'
      
